/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EducationRouteImport } from './routes/education'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingDiagnosticRouteImport } from './routes/onboarding.diagnostic'
import { Route as OnboardingProfilRouteImport } from './routes/onboarding.profil'
import { Route as OnboardingVerificationRouteImport } from './routes/onboarding.verification'
import { Route as OnboardingDiagnosticResultatRouteImport } from './routes/onboarding.diagnostic.resultat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDiagnosticRoute = OnboardingDiagnosticRouteImport.update({
  id: '/onboarding/diagnostic',
  path: '/onboarding/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProfilRoute = OnboardingProfilRouteImport.update({
  id: '/onboarding/profil',
  path: '/onboarding/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVerificationRoute = OnboardingVerificationRouteImport.update({
  id: '/onboarding/verification',
  path: '/onboarding/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDiagnosticResultatRoute =
  OnboardingDiagnosticResultatRouteImport.update({
    id: '/resultat',
    path: '/resultat',
    getParentRoute: () => OnboardingDiagnosticRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/education': typeof EducationRoute
  '/historique': typeof HistoriqueRoute
  '/parametres': typeof ParametresRoute
  '/simulateur': typeof SimulateurRoute
  '/onboarding/diagnostic': typeof OnboardingDiagnosticRouteWithChildren
  '/onboarding/profil': typeof OnboardingProfilRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/onboarding/diagnostic/resultat': typeof OnboardingDiagnosticResultatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/education': typeof EducationRoute
  '/historique': typeof HistoriqueRoute
  '/parametres': typeof ParametresRoute
  '/simulateur': typeof SimulateurRoute
  '/onboarding/diagnostic': typeof OnboardingDiagnosticRouteWithChildren
  '/onboarding/profil': typeof OnboardingProfilRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/onboarding/diagnostic/resultat': typeof OnboardingDiagnosticResultatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/education': typeof EducationRoute
  '/historique': typeof HistoriqueRoute
  '/parametres': typeof ParametresRoute
  '/simulateur': typeof SimulateurRoute
  '/onboarding/diagnostic': typeof OnboardingDiagnosticRouteWithChildren
  '/onboarding/profil': typeof OnboardingProfilRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/onboarding/diagnostic/resultat': typeof OnboardingDiagnosticResultatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/documents'
    | '/education'
    | '/historique'
    | '/parametres'
    | '/simulateur'
    | '/onboarding/diagnostic'
    | '/onboarding/profil'
    | '/onboarding/verification'
    | '/onboarding/'
    | '/onboarding/diagnostic/resultat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/documents'
    | '/education'
    | '/historique'
    | '/parametres'
    | '/simulateur'
    | '/onboarding/diagnostic'
    | '/onboarding/profil'
    | '/onboarding/verification'
    | '/onboarding'
    | '/onboarding/diagnostic/resultat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/documents'
    | '/education'
    | '/historique'
    | '/parametres'
    | '/simulateur'
    | '/onboarding/diagnostic'
    | '/onboarding/profil'
    | '/onboarding/verification'
    | '/onboarding/'
    | '/onboarding/diagnostic/resultat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EducationRoute: typeof EducationRoute
  HistoriqueRoute: typeof HistoriqueRoute
  ParametresRoute: typeof ParametresRoute
  SimulateurRoute: typeof SimulateurRoute
  OnboardingDiagnosticRoute: typeof OnboardingDiagnosticRouteWithChildren
  OnboardingProfilRoute: typeof OnboardingProfilRoute
  OnboardingVerificationRoute: typeof OnboardingVerificationRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/diagnostic': {
      id: '/onboarding/diagnostic'
      path: '/onboarding/diagnostic'
      fullPath: '/onboarding/diagnostic'
      preLoaderRoute: typeof OnboardingDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/profil': {
      id: '/onboarding/profil'
      path: '/onboarding/profil'
      fullPath: '/onboarding/profil'
      preLoaderRoute: typeof OnboardingProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/verification': {
      id: '/onboarding/verification'
      path: '/onboarding/verification'
      fullPath: '/onboarding/verification'
      preLoaderRoute: typeof OnboardingVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/diagnostic/resultat': {
      id: '/onboarding/diagnostic/resultat'
      path: '/resultat'
      fullPath: '/onboarding/diagnostic/resultat'
      preLoaderRoute: typeof OnboardingDiagnosticResultatRouteImport
      parentRoute: typeof OnboardingDiagnosticRoute
    }
  }
}

interface OnboardingDiagnosticRouteChildren {
  OnboardingDiagnosticResultatRoute: typeof OnboardingDiagnosticResultatRoute
}

const OnboardingDiagnosticRouteChildren: OnboardingDiagnosticRouteChildren = {
  OnboardingDiagnosticResultatRoute: OnboardingDiagnosticResultatRoute,
}

const OnboardingDiagnosticRouteWithChildren =
  OnboardingDiagnosticRoute._addFileChildren(OnboardingDiagnosticRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EducationRoute: EducationRoute,
  HistoriqueRoute: HistoriqueRoute,
  ParametresRoute: ParametresRoute,
  SimulateurRoute: SimulateurRoute,
  OnboardingDiagnosticRoute: OnboardingDiagnosticRouteWithChildren,
  OnboardingProfilRoute: OnboardingProfilRoute,
  OnboardingVerificationRoute: OnboardingVerificationRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
